name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Android APK
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk
          runner-python-version: '3.11'

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SolarMeterApp
          path: build/apk/**/*.apk
